import os
from dotenv import load_dotenv
from google import genai
from google.genai import errors
from backend.utils.prompts import (
    SUMMARY_PROMPT,
    KEY_POINTS_PROMPT,
    RESEARCH_GAPS_PROMPT,
    PROJECT_IDEAS_PROMPT,
    VIVA_PROMPT,
    RAG_CHAT_PROMPT
)

# Load environment variables
load_dotenv()
# Also check parent directory .env if not found
if not os.getenv("GEMINI_API_KEY"):
    parent_env = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), ".env")
    if os.path.exists(parent_env):
        load_dotenv(parent_env)

DEFAULT_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

def get_gemini_client() -> genai.Client:
    """
    Returns an authenticated Google GenAI client.
    Raises RuntimeError if GEMINI_API_KEY is missing.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or api_key.strip() == "" or api_key.startswith("your_"):
        raise RuntimeError(
            "GEMINI_API_KEY is missing or unconfigured. Please add your Gemini API key to backend/.env."
        )
    return genai.Client(api_key=api_key.strip())


def generate_content(prompt: str, model_name: str = None) -> str:
    """
    Sends prompt to the Gemini API and returns the generated text response.
    Handles errors gracefully with helpful diagnostics.
    """
    model = model_name or os.getenv("GEMINI_MODEL", DEFAULT_MODEL)
    client = get_gemini_client()

    try:
        response = client.models.generate_content(
            model=model,
            contents=prompt,
        )
        if response and response.text:
            return response.text.strip()
        return "No response text was generated by Gemini."

    except errors.APIError as e:
        # Handle specific Gemini API errors (e.g. rate limit, quota, invalid key)
        msg = str(e)
        if "RESOURCE_EXHAUSTED" in msg or "429" in msg:
            raise RuntimeError("Gemini API rate limit or quota exceeded. Please try again shortly.")
        elif "PERMISSION_DENIED" in msg or "API_KEY_INVALID" in msg:
            raise RuntimeError("Invalid Gemini API key. Please verify your GEMINI_API_KEY in backend/.env.")
        elif "NOT_FOUND" in msg:
            # Fallback model attempt if specific model is not found in user tier
            if model != "gemini-1.5-flash":
                return generate_content(prompt, model_name="gemini-1.5-flash")
            raise RuntimeError(f"Gemini model '{model}' not found or unavailable.")
        raise RuntimeError(f"Gemini API error: {msg}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error communicating with Gemini API: {str(e)}")


def generate_summary(paper_text: str) -> str:
    prompt = SUMMARY_PROMPT.format(text=paper_text[:25000])
    return generate_content(prompt)


def generate_key_points(paper_text: str) -> str:
    prompt = KEY_POINTS_PROMPT.format(text=paper_text[:25000])
    return generate_content(prompt)


def generate_research_gaps(paper_text: str) -> str:
    prompt = RESEARCH_GAPS_PROMPT.format(text=paper_text[:25000])
    return generate_content(prompt)


def generate_project_ideas(paper_text: str) -> str:
    prompt = PROJECT_IDEAS_PROMPT.format(text=paper_text[:25000])
    return generate_content(prompt)


def generate_viva_questions(paper_text: str) -> str:
    prompt = VIVA_PROMPT.format(text=paper_text[:25000])
    return generate_content(prompt)


def answer_rag_question(question: str, context_chunks: list[str]) -> str:
    """
    Generates a grounded response using retrieved context chunks.
    """
    context_str = "\n\n---\n\n".join(context_chunks)
    prompt = RAG_CHAT_PROMPT.format(context=context_str, question=question)
    return generate_content(prompt)
